### ISSUE TITLE
Runtime/HttpConnect Exceptions

### ISSUE THREAD

**Issue by Ragnarocek** [sunecz/Media-Downloader#13]
Zdravim,

predpokladam, ze chyby su sposobene nedostupnostou webu projektu...

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at sune.app.mediadown.util.Utils$Internal.throwRuntimeException(Utils.java:1810)
	at sune.app.mediadown.util.Utils$Suppress.lambda$2(Utils.java:2840)
	at sune.app.mediadown.util.Utils$Suppress.lambda$1(Utils.java:2821)
	at sune.app.mediadown.util.Utils$Ignore$Cancellation.callVoid(Utils.java:3009)
	at sune.app.mediadown.util.Utils$Ignore$Cancellation.callVoid(Utils.java:2999)
	at sune.app.mediadown.drm.DecryptionTransformer$DecryptionKeyObtainPipelineTask.doRun(DecryptionTransformer.java:210)
	at sune.app.mediadown.pipeline.AbstractPipelineTask.run(AbstractPipelineTask.java:58)
	at sune.app.mediadown.pipeline.Pipeline.invoke(Pipeline.java:115)
	at sune.app.mediadown.pipeline.Pipeline.runnable(Pipeline.java:134)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at sune.app.mediadown.net.Web.doRequest(Web.java:214)
	at sune.app.mediadown.net.Web.doRequest(Web.java:256)
	at sune.app.mediadown.net.Web.requestStream(Web.java:289)
	at sune.app.mediadown.drm.util.WV$API.request(WV.java:37)
	at sune.app.mediadown.drm.util.WV$API.generateLicenseRequest(WV.java:46)
	at sune.app.mediadown.drm.DecryptionKeyObtainer.obtainDecryptionKeys(DecryptionKeyObtainer.java:244)
	at sune.app.mediadown.drm.DecryptionKeyObtainer.decryptionKeys(DecryptionKeyObtainer.java:280)
	at sune.app.mediadown.drm.DecryptionKeyObtainer.start(DecryptionKeyObtainer.java:385)
	at sune.app.mediadown.util.Utils$Suppress.lambda$2(Utils.java:2837)
	... 8 more
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.cancel(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(Unknown Source)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
Caused by: java.net.ConnectException: HTTP connect timed out
	... 13 more

**Comment by sunecz** [comment]
Zdravím,

ano, chyby jsou dočasně způsobené nedostupností webových stránek. Řeším technické problémy se serverem. Pokud nenarazím na nějaký závažný problém, tak ještě během dneška by to mělo vyřešeno.

**Comment by sunecz** [comment]
Technický problém vyřešen, tak už by to mělo být vše v pořádku.
