### ISSUE TITLE
Nelze získat klíče z CT na Win7

### ISSUE THREAD

**Issue by huh02** [sunecz/Media-Downloader#4]
Dostávám chybu ve Win7 (00.02.09-dev.18)

java.lang.RuntimeException: java.lang.IllegalStateException: Decryption key for video not found
	at sune.app.mediadown.util.Utils$Internal.throwRuntimeException(Utils.java:1767)
	at sune.app.mediadown.util.Utils$Suppress.lambda$2(Utils.java:2797)
	at sune.app.mediadown.util.Utils$Suppress.lambda$1(Utils.java:2778)
	at sune.app.mediadown.util.Utils$Ignore$Cancellation.callVoid(Utils.java:2966)
	at sune.app.mediadown.util.Utils$Ignore$Cancellation.callVoid(Utils.java:2956)
	at sune.app.mediadown.drm.DecryptionTransformer$DecryptionKeyObtainPipelineTask.doRun(DecryptionTransformer.java:210)
	at sune.app.mediadown.pipeline.AbstractPipelineTask.run(AbstractPipelineTask.java:58)
	at sune.app.mediadown.pipeline.Pipeline.invoke(Pipeline.java:115)
	at sune.app.mediadown.pipeline.Pipeline.runnable(Pipeline.java:134)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Decryption key for video not found
	at sune.app.mediadown.drm.DecryptionKeyObtainer.start(DecryptionKeyObtainer.java:358)
	at sune.app.mediadown.util.Utils$Suppress.lambda$2(Utils.java:2794)
	... 8 more

Je to bug nebo není aplikace kompatibilní s Win7?
Pokud není program kompatibilní, mělo by to být uvedeno, nenašel jsem od které verze Windows x64 je možné aplikaci používat.

**Comment by sunecz** [comment]
Zdravím,

program funguje i na Windows 7, co tam ale očividně nefunguje je jen vlastní program (wv.exe), který se používá k získávání dešifrovacích klíčů.

Sestavil jsem ho znovu, mělo by to fungovat i na Windows 7. Otestoval jsem to u sebe ve VM. Odkaz zde: https://app.sune.tech/mediadown/tmp/wv_win7-2024_02_10.zip Extrahujte archív a soubor wv.exe vložte do složky resources/binary/drm a přepište stávající soubor.

Prosím, zkuste to u sebe a dejte mi vědět. Pokud to bude fungovat i u Vás, integruju to do programu, aby se to nemuselo stahovat manuálně.

**Comment by huh02** [comment]
Nahradil jsem wv.exe ve složce \resources\binary\drm  a zdá se, že to funguje, perfektní.
Velké díky!

**Comment by sunecz** [comment]
Díky za vyzkoušení a potvrzení! Integroval jsem to do programu, není tedy případně již potřeba nic manuálně stahovat.
